/* 全部词库 · CEFR A1 / A2 / B1，共 1925 词（A1 460 / A2 465 / B1 1000）
   格式：[英文, 中文, 类别, 难度, 词性]   难度：1=A1  2=A2  3=B1
   词性只有五种：n 名词 / v 动词 / adj 形容词 / adv 副词 / num 数词（中文名在 POS_CN 里）。

   **一个难度就是一章，章与章之间的词不重复**（用户定的）：
   第一章「石廊」只出难度 1，第二章「锈庭」只出难度 2，难度 3 留给还没做的第三章。
   哪一章用哪个难度写在 content.js 的 `CHAPTERS[].wordLv` 上。
   加词直接往 WORDS 里加，**五个字段都要给**；类别要在 CAT_CN 里有对应中文名。
   **英文不能重复** —— WMAP 按英文做键，重了会静默覆盖。
   **同一难度里中文释义也不能重复** —— 选择题的干扰项就在同难度里挑，
   两个词共用一个中文会出现「两个选项都对」。加词后跑一遍同级释义查重。
   **每个难度的每个类别、每个词性都要 ≥6 个词** —— 普通怪按类别出题，
   Boss 弱点按词性挑（game.js 的 chapterPos()），不够 6 个就挑不到。
   **英文最长 11 个字母** —— 拼写题的字格只量到 11，再长会在 390×667 上折行。
   虚词（func：代词/介词/连词/冠词）已经整类删掉了（用户 2026-09），别加回来。
   怪物按类别出题（见 content.js 里每只怪的 cat 字段）。*/
"use strict";

var CAT_CN = {
  animal:"动物", food:"食物", color:"颜色", body:"身体", people:"人",
  thing:"物品", nature:"自然", verb:"动作", adj:"描述",
  time:"时间", place:"地点", feel:"情绪",
  num:"数字", adv:"副词"
};

/* 词性的中文名 —— Boss 弱点那行文案用它（game.js 的 showWeak）*/
var POS_CN = { n:"名词", v:"动词", adj:"形容词", adv:"副词", num:"数词" };

var WORDS = [
/* ═══════ 难度 1　A1 · 第一章「石廊」　共 460 词 ═══════ */
/* 动物 24 */
["cat","猫","animal",1,"n"],["dog","狗","animal",1,"n"],["bird","鸟","animal",1,"n"],
["fish","鱼","animal",1,"n"],["horse","马","animal",1,"n"],["pig","猪","animal",1,"n"],
["cow","奶牛","animal",1,"n"],["duck","鸭子","animal",1,"n"],["rabbit","兔子","animal",1,"n"],
["mouse","老鼠","animal",1,"n"],["bear","熊","animal",1,"n"],["tiger","老虎","animal",1,"n"],
["lion","狮子","animal",1,"n"],["monkey","猴子","animal",1,"n"],["sheep","绵羊","animal",1,"n"],
["chicken","鸡","animal",1,"n"],["elephant","大象","animal",1,"n"],["panda","熊猫","animal",1,"n"],
["fox","狐狸","animal",1,"n"],["hen","母鸡","animal",1,"n"],["spider","蜘蛛","animal",1,"n"],
["butterfly","蝴蝶","animal",1,"n"],["animal","动物","animal",1,"n"],["pet","宠物","animal",1,"n"],
/* 食物 35 */
["bread","面包","food",1,"n"],["milk","牛奶","food",1,"n"],["egg","鸡蛋","food",1,"n"],
["rice","米饭","food",1,"n"],["apple","苹果","food",1,"n"],["banana","香蕉","food",1,"n"],
["water","水","food",1,"n"],["meat","肉","food",1,"n"],["cake","蛋糕","food",1,"n"],
["soup","汤","food",1,"n"],["tea","茶","food",1,"n"],["juice","果汁","food",1,"n"],
["sugar","糖","food",1,"n"],["salt","盐","food",1,"n"],["noodles","面条","food",1,"n"],
["coffee","咖啡","food",1,"n"],["fruit","水果","food",1,"n"],["vegetable","蔬菜","food",1,"n"],
["beef","牛肉","food",1,"n"],["pork","猪肉","food",1,"n"],["orange","橙子","food",1,"n"],
["chocolate","巧克力","food",1,"n"],["candy","糖果","food",1,"n"],["cookie","曲奇","food",1,"n"],
["sandwich","三明治","food",1,"n"],["pizza","比萨","food",1,"n"],["breakfast","早餐","food",1,"n"],
["lunch","午餐","food",1,"n"],["dinner","晚餐","food",1,"n"],["meal","一顿饭","food",1,"n"],
["food","食物","food",1,"n"],["dish","菜肴","food",1,"n"],["menu","菜单","food",1,"n"],
["oil","油","food",1,"n"],["corn","玉米","food",1,"n"],
/* 颜色 10 */
["red","红色的","color",1,"adj"],["blue","蓝色的","color",1,"adj"],["green","绿色的","color",1,"adj"],
["yellow","黄色的","color",1,"adj"],["black","黑色的","color",1,"adj"],["white","白色的","color",1,"adj"],
["brown","棕色的","color",1,"adj"],["pink","粉色的","color",1,"adj"],["colour","颜色","color",1,"n"],
["colourful","色彩鲜艳的","color",1,"adj"],
/* 身体 19 */
["hand","手","body",1,"n"],["head","头","body",1,"n"],["eye","眼睛","body",1,"n"],
["ear","耳朵","body",1,"n"],["nose","鼻子","body",1,"n"],["mouth","嘴","body",1,"n"],
["foot","脚","body",1,"n"],["hair","头发","body",1,"n"],["arm","手臂","body",1,"n"],
["leg","腿","body",1,"n"],["face","脸","body",1,"n"],["body","身体","body",1,"n"],
["back","后背","body",1,"n"],["neck","脖子","body",1,"n"],["heart","心脏","body",1,"n"],
["toe","脚趾","body",1,"n"],["lip","嘴唇","body",1,"n"],["tongue","舌头","body",1,"n"],
["brain","大脑","body",1,"n"],
/* 人 29 */
["mother","妈妈","people",1,"n"],["father","爸爸","people",1,"n"],["sister","姐妹","people",1,"n"],
["brother","兄弟","people",1,"n"],["family","家庭","people",1,"n"],["friend","朋友","people",1,"n"],
["baby","婴儿","people",1,"n"],["boy","男孩","people",1,"n"],["girl","女孩","people",1,"n"],
["teacher","老师","people",1,"n"],["man","男人","people",1,"n"],["woman","女人","people",1,"n"],
["child","孩子","people",1,"n"],["people","人们","people",1,"n"],["person","个人","people",1,"n"],
["student","学生","people",1,"n"],["doctor","医生","people",1,"n"],["nurse","护士","people",1,"n"],
["police","警察","people",1,"n"],["driver","司机","people",1,"n"],["worker","工人","people",1,"n"],
["son","儿子","people",1,"n"],["daughter","女儿","people",1,"n"],["grandmother","奶奶","people",1,"n"],
["grandfather","爷爷","people",1,"n"],["uncle","叔叔","people",1,"n"],["aunt","姑姑","people",1,"n"],
["husband","丈夫","people",1,"n"],["wife","妻子","people",1,"n"],
/* 物品 55 */
["book","书","thing",1,"n"],["pen","钢笔","thing",1,"n"],["chair","椅子","thing",1,"n"],
["table","桌子","thing",1,"n"],["door","门","thing",1,"n"],["window","窗户","thing",1,"n"],
["bed","床","thing",1,"n"],["box","盒子","thing",1,"n"],["key","钥匙","thing",1,"n"],
["bag","包","thing",1,"n"],["clock","钟","thing",1,"n"],["cup","杯子","thing",1,"n"],
["phone","电话","thing",1,"n"],["car","汽车","thing",1,"n"],["bike","自行车","thing",1,"n"],
["ball","球","thing",1,"n"],["shoe","鞋","thing",1,"n"],["hat","帽子","thing",1,"n"],
["coat","外套","thing",1,"n"],["map","地图","thing",1,"n"],["bus","公共汽车","thing",1,"n"],
["train","火车","thing",1,"n"],["plane","飞机","thing",1,"n"],["boat","小船","thing",1,"n"],
["desk","书桌","thing",1,"n"],["paper","纸","thing",1,"n"],["pencil","铅笔","thing",1,"n"],
["bottle","瓶子","thing",1,"n"],["plate","盘子","thing",1,"n"],["bowl","碗","thing",1,"n"],
["knife","刀","thing",1,"n"],["fork","叉子","thing",1,"n"],["spoon","勺子","thing",1,"n"],
["glass","玻璃杯","thing",1,"n"],["radio","收音机","thing",1,"n"],["computer","电脑","thing",1,"n"],
["camera","相机","thing",1,"n"],["picture","图画","thing",1,"n"],["photo","照片","thing",1,"n"],
["letter","信","thing",1,"n"],["card","卡片","thing",1,"n"],["money","钱","thing",1,"n"],
["watch","手表","thing",1,"n"],["ring","戒指","thing",1,"n"],["dress","连衣裙","thing",1,"n"],
["shirt","衬衫","thing",1,"n"],["trousers","裤子","thing",1,"n"],["sock","袜子","thing",1,"n"],
["skirt","短裙","thing",1,"n"],["jacket","夹克","thing",1,"n"],["toy","玩具","thing",1,"n"],
["game","游戏","thing",1,"n"],["music","音乐","thing",1,"n"],["film","电影","thing",1,"n"],
["wall","墙","thing",1,"n"],
/* 自然 28 */
["sun","太阳","nature",1,"n"],["moon","月亮","nature",1,"n"],["star","星星","nature",1,"n"],
["tree","树","nature",1,"n"],["flower","花","nature",1,"n"],["rain","雨","nature",1,"n"],
["snow","雪","nature",1,"n"],["wind","风","nature",1,"n"],["fire","火","nature",1,"n"],
["stone","石头","nature",1,"n"],["river","河","nature",1,"n"],["mountain","山","nature",1,"n"],
["sky","天空","nature",1,"n"],["sea","海","nature",1,"n"],["night","夜晚","nature",1,"n"],
["day","白天","nature",1,"n"],["cloud","云","nature",1,"n"],["grass","草","nature",1,"n"],
["leaf","树叶","nature",1,"n"],["lake","湖","nature",1,"n"],["field","田野","nature",1,"n"],
["hill","小山","nature",1,"n"],["earth","地球","nature",1,"n"],["world","世界","nature",1,"n"],
["air","空气","nature",1,"n"],["weather","天气","nature",1,"n"],["plant","植物","nature",1,"n"],
["wood","木头","nature",1,"n"],
/* 动作 80 */
["run","跑","verb",1,"v"],["walk","走","verb",1,"v"],["eat","吃","verb",1,"v"],
["drink","喝","verb",1,"v"],["sleep","睡觉","verb",1,"v"],["read","读","verb",1,"v"],
["write","写","verb",1,"v"],["sing","唱歌","verb",1,"v"],["jump","跳","verb",1,"v"],
["open","打开","verb",1,"v"],["close","关上","verb",1,"v"],["look","看","verb",1,"v"],
["sit","坐","verb",1,"v"],["stand","站","verb",1,"v"],["give","给","verb",1,"v"],
["help","帮助","verb",1,"v"],["come","来","verb",1,"v"],["go","去","verb",1,"v"],
["take","拿","verb",1,"v"],["find","找到","verb",1,"v"],["be","是","verb",1,"v"],
["have","有","verb",1,"v"],["do","做","verb",1,"v"],["make","制作","verb",1,"v"],
["say","说","verb",1,"v"],["tell","告诉","verb",1,"v"],["ask","问","verb",1,"v"],
["answer","回答","verb",1,"v"],["know","知道","verb",1,"v"],["think","思考","verb",1,"v"],
["want","想要","verb",1,"v"],["like","喜欢","verb",1,"v"],["need","需要","verb",1,"v"],
["work","工作","verb",1,"v"],["play","玩","verb",1,"v"],["study","学习","verb",1,"v"],
["learn","学会","verb",1,"v"],["teach","教","verb",1,"v"],["see","看见","verb",1,"v"],
["hear","听见","verb",1,"v"],["listen","倾听","verb",1,"v"],["speak","讲","verb",1,"v"],
["talk","交谈","verb",1,"v"],["call","呼叫","verb",1,"v"],["use","使用","verb",1,"v"],
["put","放置","verb",1,"v"],["get","得到","verb",1,"v"],["buy","买","verb",1,"v"],
["pay","付钱","verb",1,"v"],["sell","卖","verb",1,"v"],["cook","做饭","verb",1,"v"],
["wash","洗","verb",1,"v"],["clean","打扫","verb",1,"v"],["wear","穿着","verb",1,"v"],
["start","开始","verb",1,"v"],["stop","停止","verb",1,"v"],["finish","完成","verb",1,"v"],
["try","尝试","verb",1,"v"],["live","居住","verb",1,"v"],["stay","停留","verb",1,"v"],
["leave","离开","verb",1,"v"],["wait","等待","verb",1,"v"],["meet","遇见","verb",1,"v"],
["visit","拜访","verb",1,"v"],["travel","旅行","verb",1,"v"],["drive","驾驶","verb",1,"v"],
["ride","骑","verb",1,"v"],["fly","飞","verb",1,"v"],["swim","游泳","verb",1,"v"],
["dance","跳舞","verb",1,"v"],["draw","画画","verb",1,"v"],["build","建造","verb",1,"v"],
["carry","搬运","verb",1,"v"],["bring","带来","verb",1,"v"],["send","寄送","verb",1,"v"],
["show","展示","verb",1,"v"],["move","移动","verb",1,"v"],["turn","转动","verb",1,"v"],
["push","推","verb",1,"v"],["pull","拉","verb",1,"v"],
/* 描述 53 */
["big","大的","adj",1,"adj"],["small","小的","adj",1,"adj"],["hot","热的","adj",1,"adj"],
["cold","冷的","adj",1,"adj"],["good","好的","adj",1,"adj"],["bad","坏的","adj",1,"adj"],
["new","新的","adj",1,"adj"],["old","旧的","adj",1,"adj"],["happy","快乐的","adj",1,"adj"],
["sad","伤心的","adj",1,"adj"],["fast","快的","adj",1,"adj"],["slow","慢的","adj",1,"adj"],
["long","长的","adj",1,"adj"],["short","短的","adj",1,"adj"],["strong","强壮的","adj",1,"adj"],
["tired","累的","adj",1,"adj"],["young","年轻的","adj",1,"adj"],["tall","个子高的","adj",1,"adj"],
["high","高的","adj",1,"adj"],["low","低的","adj",1,"adj"],["little","小小的","adj",1,"adj"],
["large","大型的","adj",1,"adj"],["nice","不错的","adj",1,"adj"],["fine","挺好的","adj",1,"adj"],
["great","了不起的","adj",1,"adj"],["beautiful","美丽的","adj",1,"adj"],["pretty","漂亮的","adj",1,"adj"],
["dirty","脏的","adj",1,"adj"],["wet","湿的","adj",1,"adj"],["dry","干的","adj",1,"adj"],
["warm","温暖的","adj",1,"adj"],["cool","凉爽的","adj",1,"adj"],["rich","富有的","adj",1,"adj"],
["poor","贫穷的","adj",1,"adj"],["easy","容易的","adj",1,"adj"],["hard","难的","adj",1,"adj"],
["busy","忙碌的","adj",1,"adj"],["free","自由的","adj",1,"adj"],["ready","准备好的","adj",1,"adj"],
["hungry","饥饿的","adj",1,"adj"],["thirsty","口渴的","adj",1,"adj"],["ill","生病的","adj",1,"adj"],
["right","正确的","adj",1,"adj"],["wrong","错误的","adj",1,"adj"],["true","真的","adj",1,"adj"],
["same","相同的","adj",1,"adj"],["different","不同的","adj",1,"adj"],["lovely","可爱的","adj",1,"adj"],
["funny","滑稽的","adj",1,"adj"],["important","重要的","adj",1,"adj"],["delicious","美味的","adj",1,"adj"],
["sweet","甜的","adj",1,"adj"],["soft","柔软的","adj",1,"adj"],
/* 时间 26 */
["afternoon","下午","time",1,"n"],["evening","傍晚","time",1,"n"],["month","月份","time",1,"n"],
["yesterday","昨天","time",1,"n"],["morning","早晨","time",1,"n"],["week","星期","time",1,"n"],
["year","年","time",1,"n"],["today","今天","time",1,"n"],["tomorrow","明天","time",1,"n"],
["time","时间","time",1,"n"],["date","日期","time",1,"n"],["birthday","生日","time",1,"n"],
["holiday","假日","time",1,"n"],["weekend","周末","time",1,"n"],["noon","中午","time",1,"n"],
["early","早的","time",1,"adj"],["late","晚的","time",1,"adj"],["age","年龄","time",1,"n"],
["now","现在","time",1,"adv"],["Monday","星期一","time",1,"n"],["Tuesday","星期二","time",1,"n"],
["Wednesday","星期三","time",1,"n"],["Thursday","星期四","time",1,"n"],["Friday","星期五","time",1,"n"],
["Saturday","星期六","time",1,"n"],["Sunday","星期日","time",1,"n"],
/* 地点 26 */
["park","公园","place",1,"n"],["city","城市","place",1,"n"],["town","小镇","place",1,"n"],
["street","街道","place",1,"n"],["garden","花园","place",1,"n"],["school","学校","place",1,"n"],
["shop","商店","place",1,"n"],["home","家","place",1,"n"],["room","房间","place",1,"n"],
["house","房子","place",1,"n"],["flat","公寓","place",1,"n"],["kitchen","厨房","place",1,"n"],
["bedroom","卧室","place",1,"n"],["bathroom","浴室","place",1,"n"],["office","办公室","place",1,"n"],
["hotel","旅馆","place",1,"n"],["restaurant","餐馆","place",1,"n"],["bank","银行","place",1,"n"],
["farm","农场","place",1,"n"],["zoo","动物园","place",1,"n"],["cinema","电影院","place",1,"n"],
["country","国家","place",1,"n"],["road","公路","place",1,"n"],["way","路线","place",1,"n"],
["place","地方","place",1,"n"],["building","建筑","place",1,"n"],
/* 情绪 19 */
["love","爱","feel",1,"v"],["fun","有趣的","feel",1,"adj"],["glad","高兴的","feel",1,"adj"],
["sorry","抱歉的","feel",1,"adj"],["worry","担心","feel",1,"v"],["calm","平静的","feel",1,"adj"],
["shy","害羞的","feel",1,"adj"],["miss","想念","feel",1,"v"],["kind","善良的","feel",1,"adj"],
["feeling","感受","feel",1,"n"],["wish","愿望","feel",1,"n"],["thank","感谢","feel",1,"v"],
["welcome","欢迎","feel",1,"v"],["enjoy","喜爱","feel",1,"v"],["luck","运气","feel",1,"n"],
["hate","讨厌","feel",1,"v"],["care","关心","feel",1,"v"],["dream","梦想","feel",1,"n"],
["smile","微笑","feel",1,"v"],
/* 数字 26 */
["one","一","num",1,"num"],["two","二","num",1,"num"],["three","三","num",1,"num"],
["four","四","num",1,"num"],["five","五","num",1,"num"],["six","六","num",1,"num"],
["seven","七","num",1,"num"],["eight","八","num",1,"num"],["nine","九","num",1,"num"],
["ten","十","num",1,"num"],["eleven","十一","num",1,"num"],["twelve","十二","num",1,"num"],
["twenty","二十","num",1,"num"],["thirty","三十","num",1,"num"],["forty","四十","num",1,"num"],
["fifty","五十","num",1,"num"],["hundred","一百","num",1,"num"],["thousand","一千","num",1,"num"],
["zero","零","num",1,"num"],["first","第一","num",1,"num"],["second","第二","num",1,"num"],
["number","数目","num",1,"num"],["many","许多","num",1,"num"],["much","大量","num",1,"num"],
["few","少数","num",1,"num"],["half","一半","num",1,"num"],
/* 副词 30 */
["very","非常","adv",1,"adv"],["too","太","adv",1,"adv"],["also","也","adv",1,"adv"],
["only","仅仅","adv",1,"adv"],["just","刚刚","adv",1,"adv"],["again","再次","adv",1,"adv"],
["still","仍然","adv",1,"adv"],["already","已经","adv",1,"adv"],["soon","不久","adv",1,"adv"],
["then","然后","adv",1,"adv"],["here","这里","adv",1,"adv"],["there","那里","adv",1,"adv"],
["always","总是","adv",1,"adv"],["never","从不","adv",1,"adv"],["often","经常","adv",1,"adv"],
["sometimes","有时","adv",1,"adv"],["usually","通常","adv",1,"adv"],["together","一起","adv",1,"adv"],
["maybe","也许","adv",1,"adv"],["really","确实","adv",1,"adv"],["well","很好地","adv",1,"adv"],
["quickly","迅速地","adv",1,"adv"],["slowly","缓慢地","adv",1,"adv"],["carefully","仔细地","adv",1,"adv"],
["almost","差不多","adv",1,"adv"],["enough","足够","adv",1,"adv"],["more","更多","adv",1,"adv"],
["most","最多","adv",1,"adv"],["less","更少","adv",1,"adv"],["ago","以前","adv",1,"adv"],
/* ═══════ 难度 2　A2 · 第二章「锈庭」　共 465 词 ═══════ */
/* 动物 25 */
["wolf","狼","animal",2,"n"],["snake","蛇","animal",2,"n"],["bee","蜜蜂","animal",2,"n"],
["ant","蚂蚁","animal",2,"n"],["goat","山羊","animal",2,"n"],["deer","鹿","animal",2,"n"],
["frog","青蛙","animal",2,"n"],["eagle","鹰","animal",2,"n"],["shark","鲨鱼","animal",2,"n"],
["goose","鹅","animal",2,"n"],["owl","猫头鹰","animal",2,"n"],["mosquito","蚊子","animal",2,"n"],
["whale","鲸","animal",2,"n"],["lizard","蜥蜴","animal",2,"n"],["worm","虫子","animal",2,"n"],
["snail","蜗牛","animal",2,"n"],["pigeon","鸽子","animal",2,"n"],["donkey","驴","animal",2,"n"],
["dragon","龙","animal",2,"n"],["giraffe","长颈鹿","animal",2,"n"],["camel","骆驼","animal",2,"n"],
["dolphin","海豚","animal",2,"n"],["turtle","乌龟","animal",2,"n"],["parrot","鹦鹉","animal",2,"n"],
["crab","螃蟹","animal",2,"n"],
/* 食物 35 */
["salad","沙拉","food",2,"n"],["cheese","奶酪","food",2,"n"],["butter","黄油","food",2,"n"],
["pepper","胡椒","food",2,"n"],["onion","洋葱","food",2,"n"],["potato","土豆","food",2,"n"],
["tomato","西红柿","food",2,"n"],["carrot","胡萝卜","food",2,"n"],["lemon","柠檬","food",2,"n"],
["grape","葡萄","food",2,"n"],["honey","蜂蜜","food",2,"n"],["sausage","香肠","food",2,"n"],
["biscuit","饼干","food",2,"n"],["wine","葡萄酒","food",2,"n"],["beer","啤酒","food",2,"n"],
["flour","面粉","food",2,"n"],["cream","奶油","food",2,"n"],["jam","果酱","food",2,"n"],
["pie","馅饼","food",2,"n"],["snack","零食","food",2,"n"],["garlic","大蒜","food",2,"n"],
["cabbage","卷心菜","food",2,"n"],["mushroom","蘑菇","food",2,"n"],["bean","豆子","food",2,"n"],
["peach","桃子","food",2,"n"],["cherry","樱桃","food",2,"n"],["pineapple","菠萝","food",2,"n"],
["nut","坚果","food",2,"n"],["sauce","酱汁","food",2,"n"],["taste","味道","food",2,"n"],
["strawberry","草莓","food",2,"n"],["hamburger","汉堡","food",2,"n"],["dumpling","饺子","food",2,"n"],
["melon","甜瓜","food",2,"n"],["pear","梨","food",2,"n"],
/* 颜色 7 */
["grey","灰色的","color",2,"adj"],["purple","紫色的","color",2,"adj"],["golden","金色的","color",2,"adj"],
["silver","银色的","color",2,"adj"],["dark","深色的","color",2,"adj"],["bright","明亮的","color",2,"adj"],
["shiny","闪亮的","color",2,"adj"],
/* 身体 27 */
["shoulder","肩膀","body",2,"n"],["knee","膝盖","body",2,"n"],["elbow","手肘","body",2,"n"],
["finger","手指","body",2,"n"],["throat","喉咙","body",2,"n"],["stomach","胃","body",2,"n"],
["tooth","牙齿","body",2,"n"],["skin","皮肤","body",2,"n"],["bone","骨头","body",2,"n"],
["blood","血","body",2,"n"],["wing","翅膀","body",2,"n"],["tail","尾巴","body",2,"n"],
["chest","胸口","body",2,"n"],["wrist","手腕","body",2,"n"],["ankle","脚踝","body",2,"n"],
["nail","指甲","body",2,"n"],["voice","嗓音","body",2,"n"],["waist","腰","body",2,"n"],
["palm","手掌","body",2,"n"],["heel","脚跟","body",2,"n"],["fist","拳头","body",2,"n"],
["sight","视力","body",2,"n"],["beard","胡须","body",2,"n"],["cheek","脸颊","body",2,"n"],
["chin","下巴","body",2,"n"],["thumb","拇指","body",2,"n"],["eyebrow","眉毛","body",2,"n"],
/* 人 33 */
["neighbour","邻居","people",2,"n"],["stranger","陌生人","people",2,"n"],["guest","客人","people",2,"n"],
["owner","主人","people",2,"n"],["soldier","士兵","people",2,"n"],["farmer","农民","people",2,"n"],
["artist","艺术家","people",2,"n"],["singer","歌手","people",2,"n"],["writer","作家","people",2,"n"],
["leader","领导者","people",2,"n"],["customer","顾客","people",2,"n"],["partner","伙伴","people",2,"n"],
["lawyer","律师","people",2,"n"],["engineer","工程师","people",2,"n"],["scientist","科学家","people",2,"n"],
["classmate","同学","people",2,"n"],["boss","老板","people",2,"n"],["actor","演员","people",2,"n"],
["president","总统","people",2,"n"],["king","国王","people",2,"n"],["queen","王后","people",2,"n"],
["hero","英雄","people",2,"n"],["team","团队","people",2,"n"],["group","小组","people",2,"n"],
["crowd","人群","people",2,"n"],["couple","一对夫妻","people",2,"n"],["adult","成年人","people",2,"n"],
["teenager","青少年","people",2,"n"],["member","成员","people",2,"n"],["tourist","游客","people",2,"n"],
["waiter","服务员","people",2,"n"],["cousin","表亲","people",2,"n"],["parent","家长","people",2,"n"],
/* 物品 55 */
["ticket","票","thing",2,"n"],["wallet","钱包","thing",2,"n"],["mirror","镜子","thing",2,"n"],
["candle","蜡烛","thing",2,"n"],["blanket","毯子","thing",2,"n"],["pillow","枕头","thing",2,"n"],
["needle","针","thing",2,"n"],["rope","绳子","thing",2,"n"],["ladder","梯子","thing",2,"n"],
["hammer","锤子","thing",2,"n"],["basket","篮子","thing",2,"n"],["envelope","信封","thing",2,"n"],
["stamp","邮票","thing",2,"n"],["engine","发动机","thing",2,"n"],["wheel","轮子","thing",2,"n"],
["screen","屏幕","thing",2,"n"],["button","纽扣","thing",2,"n"],["pocket","口袋","thing",2,"n"],
["belt","腰带","thing",2,"n"],["glove","手套","thing",2,"n"],["scarf","围巾","thing",2,"n"],
["boot","靴子","thing",2,"n"],["sweater","毛衣","thing",2,"n"],["uniform","制服","thing",2,"n"],
["suitcase","手提箱","thing",2,"n"],["curtain","窗帘","thing",2,"n"],["carpet","地毯","thing",2,"n"],
["shelf","架子","thing",2,"n"],["drawer","抽屉","thing",2,"n"],["cupboard","橱柜","thing",2,"n"],
["fridge","冰箱","thing",2,"n"],["oven","烤箱","thing",2,"n"],["kettle","水壶","thing",2,"n"],
["pan","平底锅","thing",2,"n"],["tray","托盘","thing",2,"n"],["battery","电池","thing",2,"n"],
["wire","电线","thing",2,"n"],["switch","开关","thing",2,"n"],["bell","铃铛","thing",2,"n"],
["message","消息","thing",2,"n"],["email","电子邮件","thing",2,"n"],["internet","互联网","thing",2,"n"],
["website","网站","thing",2,"n"],["password","密码","thing",2,"n"],["file","文件","thing",2,"n"],
["page","书页","thing",2,"n"],["note","便条","thing",2,"n"],["list","清单","thing",2,"n"],
["bill","账单","thing",2,"n"],["price","价格","thing",2,"n"],["umbrella","雨伞","thing",2,"n"],
["newspaper","报纸","thing",2,"n"],["towel","毛巾","thing",2,"n"],["soap","肥皂","thing",2,"n"],
["lamp","台灯","thing",2,"n"],
/* 自然 28 */
["forest","森林","nature",2,"n"],["desert","沙漠","nature",2,"n"],["island","岛","nature",2,"n"],
["valley","山谷","nature",2,"n"],["storm","暴风雨","nature",2,"n"],["thunder","雷","nature",2,"n"],
["fog","雾","nature",2,"n"],["ice","冰","nature",2,"n"],["sand","沙子","nature",2,"n"],
["rock","岩石","nature",2,"n"],["branch","树枝","nature",2,"n"],["root","根","nature",2,"n"],
["shadow","影子","nature",2,"n"],["wave","波浪","nature",2,"n"],["sunshine","阳光","nature",2,"n"],
["hole","洞","nature",2,"n"],["mud","泥","nature",2,"n"],["smoke","烟","nature",2,"n"],
["steam","蒸汽","nature",2,"n"],["coast","海岸","nature",2,"n"],["pond","池塘","nature",2,"n"],
["bush","灌木","nature",2,"n"],["soil","土壤","nature",2,"n"],["gas","气体","nature",2,"n"],
["nature","大自然","nature",2,"n"],["planet","行星","nature",2,"n"],["rainbow","彩虹","nature",2,"n"],
["seed","种子","nature",2,"n"],
/* 动作 65 */
["borrow","借入","verb",2,"v"],["lend","借出","verb",2,"v"],["climb","攀爬","verb",2,"v"],
["throw","扔","verb",2,"v"],["catch","接住","verb",2,"v"],["choose","选择","verb",2,"v"],
["decide","决定","verb",2,"v"],["explain","解释","verb",2,"v"],["repeat","重复","verb",2,"v"],
["describe","描述","verb",2,"v"],["compare","比较","verb",2,"v"],["collect","收集","verb",2,"v"],
["repair","修理","verb",2,"v"],["destroy","摧毁","verb",2,"v"],["protect","保护","verb",2,"v"],
["follow","跟随","verb",2,"v"],["hide","躲藏","verb",2,"v"],["search","搜寻","verb",2,"v"],
["arrive","到达","verb",2,"v"],["return","返回","verb",2,"v"],["prepare","准备","verb",2,"v"],
["practise","练习","verb",2,"v"],["invite","邀请","verb",2,"v"],["promise","承诺","verb",2,"v"],
["become","成为","verb",2,"v"],["change","改变","verb",2,"v"],["happen","发生","verb",2,"v"],
["grow","生长","verb",2,"v"],["keep","保持","verb",2,"v"],["hold","握住","verb",2,"v"],
["seem","似乎","verb",2,"v"],["feel","感觉","verb",2,"v"],["mean","意味着","verb",2,"v"],
["believe","相信","verb",2,"v"],["understand","明白","verb",2,"v"],["remember","记得","verb",2,"v"],
["forget","忘记","verb",2,"v"],["agree","同意","verb",2,"v"],["continue","继续","verb",2,"v"],
["offer","提供","verb",2,"v"],["lead","带领","verb",2,"v"],["point","指向","verb",2,"v"],
["touch","触摸","verb",2,"v"],["hit","击中","verb",2,"v"],["break","打破","verb",2,"v"],
["cut","切","verb",2,"v"],["win","赢得","verb",2,"v"],["lose","丢失","verb",2,"v"],
["join","加入","verb",2,"v"],["save","节省","verb",2,"v"],["spend","花费","verb",2,"v"],
["allow","允许","verb",2,"v"],["accept","接受","verb",2,"v"],["expect","期待","verb",2,"v"],
["plan","计划","verb",2,"v"],["check","检查","verb",2,"v"],["guess","猜测","verb",2,"v"],
["imagine","想象","verb",2,"v"],["share","分享","verb",2,"v"],["count","数数","verb",2,"v"],
["fill","装满","verb",2,"v"],["drop","掉落","verb",2,"v"],["lift","举起","verb",2,"v"],
["pass","经过","verb",2,"v"],["reach","够到","verb",2,"v"],
/* 描述 52 */
["heavy","重的","adj",2,"adj"],["light","轻的","adj",2,"adj"],["empty","空的","adj",2,"adj"],
["full","满的","adj",2,"adj"],["deep","深的","adj",2,"adj"],["narrow","窄的","adj",2,"adj"],
["wide","宽的","adj",2,"adj"],["sharp","锋利的","adj",2,"adj"],["smooth","光滑的","adj",2,"adj"],
["rough","粗糙的","adj",2,"adj"],["quiet","安静的","adj",2,"adj"],["loud","响亮的","adj",2,"adj"],
["strange","奇怪的","adj",2,"adj"],["famous","著名的","adj",2,"adj"],["modern","现代的","adj",2,"adj"],
["ancient","古老的","adj",2,"adj"],["safe","安全的","adj",2,"adj"],["dangerous","危险的","adj",2,"adj"],
["simple","简单的","adj",2,"adj"],["difficult","困难的","adj",2,"adj"],["interesting","有意思的","adj",2,"adj"],
["real","真实的","adj",2,"adj"],["sure","确信的","adj",2,"adj"],["clear","清楚的","adj",2,"adj"],
["near","近的","adj",2,"adj"],["far","远的","adj",2,"adj"],["whole","整个的","adj",2,"adj"],
["own","自己的","adj",2,"adj"],["main","主要的","adj",2,"adj"],["special","特别的","adj",2,"adj"],
["normal","正常的","adj",2,"adj"],["common","常见的","adj",2,"adj"],["popular","受欢迎的","adj",2,"adj"],
["perfect","完美的","adj",2,"adj"],["terrible","糟糕的","adj",2,"adj"],["wonderful","极好的","adj",2,"adj"],
["boring","令人厌烦的","adj",2,"adj"],["serious","严肃的","adj",2,"adj"],["polite","有礼貌的","adj",2,"adj"],
["rude","粗鲁的","adj",2,"adj"],["friendly","友好的","adj",2,"adj"],["honest","诚实的","adj",2,"adj"],
["clever","聪明的","adj",2,"adj"],["stupid","愚蠢的","adj",2,"adj"],["lazy","懒惰的","adj",2,"adj"],
["healthy","健康的","adj",2,"adj"],["fresh","新鲜的","adj",2,"adj"],["comfortable","舒适的","adj",2,"adj"],
["expensive","昂贵的","adj",2,"adj"],["cheap","便宜的","adj",2,"adj"],["sour","酸的","adj",2,"adj"],
["ugly","丑陋的","adj",2,"adj"],
/* 时间 33 */
["hour","小时","time",2,"n"],["minute","分钟","time",2,"n"],["season","季节","time",2,"n"],
["spring","春天","time",2,"n"],["summer","夏天","time",2,"n"],["autumn","秋天","time",2,"n"],
["winter","冬天","time",2,"n"],["future","未来","time",2,"n"],["past","过去","time",2,"n"],
["moment","时刻","time",2,"n"],["January","一月","time",2,"n"],["February","二月","time",2,"n"],
["March","三月","time",2,"n"],["April","四月","time",2,"n"],["May","五月","time",2,"n"],
["June","六月","time",2,"n"],["July","七月","time",2,"n"],["August","八月","time",2,"n"],
["September","九月","time",2,"n"],["October","十月","time",2,"n"],["November","十一月","time",2,"n"],
["December","十二月","time",2,"n"],["daily","每天的","time",2,"adj"],["history","历史","time",2,"n"],
["sunrise","日出","time",2,"n"],["sunset","日落","time",2,"n"],["weekday","工作日","time",2,"n"],
["quarter","一刻钟","time",2,"n"],["schedule","日程","time",2,"n"],["timetable","时间表","time",2,"n"],
["calendar","日历","time",2,"n"],["tonight","今晚","time",2,"n"],["midnight","午夜","time",2,"n"],
/* 地点 32 */
["station","车站","place",2,"n"],["airport","机场","place",2,"n"],["hospital","医院","place",2,"n"],
["market","市场","place",2,"n"],["library","图书馆","place",2,"n"],["factory","工厂","place",2,"n"],
["village","村庄","place",2,"n"],["bridge","桥","place",2,"n"],["corner","角落","place",2,"n"],
["gate","大门","place",2,"n"],["tower","塔","place",2,"n"],["cave","洞穴","place",2,"n"],
["cafe","咖啡馆","place",2,"n"],["university","大学","place",2,"n"],["college","学院","place",2,"n"],
["theatre","剧院","place",2,"n"],["harbour","港口","place",2,"n"],["square","广场","place",2,"n"],
["centre","中心","place",2,"n"],["area","区域","place",2,"n"],["yard","院子","place",2,"n"],
["garage","车库","place",2,"n"],["pool","游泳池","place",2,"n"],["gym","健身房","place",2,"n"],
["supermarket","超市","place",2,"n"],["capital","首都","place",2,"n"],["entrance","入口","place",2,"n"],
["exit","出口","place",2,"n"],["classroom","教室","place",2,"n"],["museum","博物馆","place",2,"n"],
["church","教堂","place",2,"n"],["beach","海滩","place",2,"n"],
/* 情绪 25 */
["angry","生气的","feel",2,"adj"],["afraid","害怕的","feel",2,"adj"],["bored","无聊的","feel",2,"adj"],
["excited","兴奋的","feel",2,"adj"],["nervous","紧张的","feel",2,"adj"],["proud","自豪的","feel",2,"adj"],
["lonely","孤独的","feel",2,"adj"],["surprised","惊讶的","feel",2,"adj"],["worried","担心的","feel",2,"adj"],
["pleased","高兴的","feel",2,"adj"],["upset","心烦的","feel",2,"adj"],["jealous","嫉妒的","feel",2,"adj"],
["confused","困惑的","feel",2,"adj"],["relaxed","放松的","feel",2,"adj"],["confident","自信的","feel",2,"adj"],
["cheerful","愉快的","feel",2,"adj"],["grateful","感激的","feel",2,"adj"],["emotion","情感","feel",2,"n"],
["mood","心情","feel",2,"n"],["tear","眼泪","feel",2,"n"],["pain","疼痛","feel",2,"n"],
["comfort","安慰","feel",2,"n"],["pity","遗憾","feel",2,"n"],["joy","欢乐","feel",2,"n"],
["interest","兴趣","feel",2,"n"],
/* 数字 20 */
["thirteen","十三","num",2,"num"],["fourteen","十四","num",2,"num"],["fifteen","十五","num",2,"num"],
["sixteen","十六","num",2,"num"],["seventeen","十七","num",2,"num"],["eighteen","十八","num",2,"num"],
["nineteen","十九","num",2,"num"],["sixty","六十","num",2,"num"],["seventy","七十","num",2,"num"],
["eighty","八十","num",2,"num"],["ninety","九十","num",2,"num"],["million","一百万","num",2,"num"],
["twice","两次","num",2,"num"],["double","双倍的","num",2,"num"],["single","单个的","num",2,"num"],
["pair","一双","num",2,"num"],["dozen","一打","num",2,"num"],["several","好几个","num",2,"num"],
["total","总数","num",2,"num"],["percent","百分比","num",2,"num"],
/* 副词 28 */
["away","离开地","adv",2,"adv"],["down","向下","adv",2,"adv"],["up","向上","adv",2,"adv"],
["out","向外","adv",2,"adv"],["off","离开","adv",2,"adv"],["around","四周","adv",2,"adv"],
["along","沿着","adv",2,"adv"],["across","横过","adv",2,"adv"],["through","穿过","adv",2,"adv"],
["inside","在里面","adv",2,"adv"],["outside","在外面","adv",2,"adv"],["upstairs","楼上","adv",2,"adv"],
["everywhere","到处","adv",2,"adv"],["anywhere","任何地方","adv",2,"adv"],["somewhere","某个地方","adv",2,"adv"],
["probably","很可能","adv",2,"adv"],["certainly","当然","adv",2,"adv"],["actually","实际上","adv",2,"adv"],
["finally","最终","adv",2,"adv"],["suddenly","突然","adv",2,"adv"],["easily","轻松地","adv",2,"adv"],
["hardly","几乎不","adv",2,"adv"],["nearly","将近","adv",2,"adv"],["instead","作为替代","adv",2,"adv"],
["however","然而","adv",2,"adv"],["else","别的","adv",2,"adv"],["even","甚至","adv",2,"adv"],
["ever","曾经","adv",2,"adv"],
/* ═══════ 难度 3　B1 · 留给第三章　共 1000 词 ═══════ */
/* 动物 30 */
["creature","生物","animal",3,"n"],["insect","昆虫","animal",3,"n"],["beast","野兽","animal",3,"n"],
["prey","猎物","animal",3,"n"],["nest","巢","animal",3,"n"],["herd","兽群","animal",3,"n"],
["feather","羽毛","animal",3,"n"],["claw","爪子","animal",3,"n"],["mammal","哺乳动物","animal",3,"n"],
["reptile","爬行动物","animal",3,"n"],["species","物种","animal",3,"n"],["predator","捕食者","animal",3,"n"],
["swarm","虫群","animal",3,"n"],["hive","蜂巢","animal",3,"n"],["fur","毛皮","animal",3,"n"],
["horn","兽角","animal",3,"n"],["fang","尖牙","animal",3,"n"],["tusk","獠牙","animal",3,"n"],
["beak","鸟喙","animal",3,"n"],["wildlife","野生动物","animal",3,"n"],["livestock","牲畜","animal",3,"n"],
["hound","猎犬","animal",3,"n"],["raven","渡鸦","animal",3,"n"],["serpent","巨蛇","animal",3,"n"],
["vulture","秃鹫","animal",3,"n"],["moth","飞蛾","animal",3,"n"],["bat","蝙蝠","animal",3,"n"],
["hare","野兔","animal",3,"n"],["crow","乌鸦","animal",3,"n"],["rodent","啮齿动物","animal",3,"n"],
/* 食物 35 */
["recipe","食谱","food",3,"n"],["flavour","味道","food",3,"n"],["ingredient","配料","food",3,"n"],
["portion","一份","food",3,"n"],["diet","饮食","food",3,"n"],["harvest","收成","food",3,"n"],
["supply","供给","food",3,"n"],["spice","香料","food",3,"n"],["grain","谷物","food",3,"n"],
["wheat","小麦","food",3,"n"],["feast","盛宴","food",3,"n"],["ration","口粮","food",3,"n"],
["broth","肉汤","food",3,"n"],["loaf","面包条","food",3,"n"],["crust","面包皮","food",3,"n"],
["yeast","酵母","food",3,"n"],["vinegar","醋","food",3,"n"],["syrup","糖浆","food",3,"n"],
["jelly","果冻","food",3,"n"],["pudding","布丁","food",3,"n"],["dessert","甜点","food",3,"n"],
["roast","烤肉","food",3,"n"],["stew","炖菜","food",3,"n"],["seafood","海鲜","food",3,"n"],
["shellfish","贝类","food",3,"n"],["beverage","饮料","food",3,"n"],["nutrition","营养","food",3,"n"],
["protein","蛋白质","food",3,"n"],["vitamin","维生素","food",3,"n"],["calorie","卡路里","food",3,"n"],
["herb","草药","food",3,"n"],["banquet","宴会","food",3,"n"],["appetizer","开胃菜","food",3,"n"],
["leftovers","剩饭","food",3,"n"],["dough","面团","food",3,"n"],
/* 颜色 12 */
["pale","苍白的","color",3,"adj"],["shade","色调","color",3,"n"],["faded","褪色的","color",3,"adj"],
["glowing","发光的","color",3,"adj"],["scarlet","猩红的","color",3,"adj"],["crimson","深红的","color",3,"adj"],
["violet","紫罗兰色的","color",3,"adj"],["amber","琥珀色的","color",3,"adj"],["ivory","象牙白的","color",3,"adj"],
["bronze","青铜色的","color",3,"adj"],["dim","昏暗的","color",3,"adj"],["vivid","鲜艳的","color",3,"adj"],
/* 身体 35 */
["muscle","肌肉","body",3,"n"],["nerve","神经","body",3,"n"],["breath","呼吸","body",3,"n"],
["wound","伤口","body",3,"n"],["scar","疤痕","body",3,"n"],["pulse","脉搏","body",3,"n"],
["spine","脊柱","body",3,"n"],["flesh","血肉","body",3,"n"],["skull","头骨","body",3,"n"],
["rib","肋骨","body",3,"n"],["limb","肢体","body",3,"n"],["joint","关节","body",3,"n"],
["lung","肺","body",3,"n"],["liver","肝脏","body",3,"n"],["kidney","肾脏","body",3,"n"],
["vein","血管","body",3,"n"],["organ","器官","body",3,"n"],["tissue","组织","body",3,"n"],
["forehead","额头","body",3,"n"],["jaw","下颌","body",3,"n"],["eyelid","眼睑","body",3,"n"],
["nostril","鼻孔","body",3,"n"],["sweat","汗水","body",3,"n"],["hip","臀部","body",3,"n"],
["thigh","大腿","body",3,"n"],["torso","躯干","body",3,"n"],["sense","感官","body",3,"n"],
["appetite","食欲","body",3,"n"],["stamina","耐力","body",3,"n"],["wrinkle","皱纹","body",3,"n"],
["gesture","手势","body",3,"n"],["posture","姿势","body",3,"n"],["reflex","反射","body",3,"n"],
["bruise","淤青","body",3,"n"],["fever","发烧","body",3,"n"],
/* 人 75 */
["witness","目击者","people",3,"n"],["expert","专家","people",3,"n"],["manager","经理","people",3,"n"],
["citizen","公民","people",3,"n"],["rival","对手","people",3,"n"],["ancestor","祖先","people",3,"n"],
["servant","仆人","people",3,"n"],["thief","小偷","people",3,"n"],["guard","守卫","people",3,"n"],
["priest","祭司","people",3,"n"],["hunter","猎人","people",3,"n"],["warrior","战士","people",3,"n"],
["knight","骑士","people",3,"n"],["wizard","巫师","people",3,"n"],["witch","女巫","people",3,"n"],
["monk","僧侣","people",3,"n"],["pilgrim","朝圣者","people",3,"n"],["merchant","商人","people",3,"n"],
["trader","贸易商","people",3,"n"],["blacksmith","铁匠","people",3,"n"],["miner","矿工","people",3,"n"],
["sailor","水手","people",3,"n"],["pirate","海盗","people",3,"n"],["captain","船长","people",3,"n"],
["general","将军","people",3,"n"],["officer","军官","people",3,"n"],["rebel","叛军","people",3,"n"],
["slave","奴隶","people",3,"n"],["master","主人","people",3,"n"],["apprentice","学徒","people",3,"n"],
["scholar","学者","people",3,"n"],["tutor","导师","people",3,"n"],["professor","教授","people",3,"n"],
["judge","法官","people",3,"n"],["jury","陪审团","people",3,"n"],["criminal","罪犯","people",3,"n"],
["victim","受害者","people",3,"n"],["suspect","嫌疑人","people",3,"n"],["prisoner","囚犯","people",3,"n"],
["beggar","乞丐","people",3,"n"],["orphan","孤儿","people",3,"n"],["widow","寡妇","people",3,"n"],
["heir","继承人","people",3,"n"],["noble","贵族","people",3,"n"],["peasant","农夫","people",3,"n"],
["tribe","部落","people",3,"n"],["clan","氏族","people",3,"n"],["society","社会","people",3,"n"],
["nation","民族","people",3,"n"],["public","公众","people",3,"n"],["audience","观众","people",3,"n"],
["crew","船员","people",3,"n"],["staff","员工","people",3,"n"],["colleague","同事","people",3,"n"],
["employer","雇主","people",3,"n"],["employee","雇员","people",3,"n"],["client","客户","people",3,"n"],
["agent","代理人","people",3,"n"],["guide","向导","people",3,"n"],["healer","治疗者","people",3,"n"],
["surgeon","外科医生","people",3,"n"],["dentist","牙医","people",3,"n"],["pilot","飞行员","people",3,"n"],
["chef","厨师","people",3,"n"],["waitress","女服务员","people",3,"n"],["librarian","图书管理员","people",3,"n"],
["journalist","记者","people",3,"n"],["editor","编辑","people",3,"n"],["author","著者","people",3,"n"],
["poet","诗人","people",3,"n"],["painter","画家","people",3,"n"],["dancer","舞者","people",3,"n"],
["athlete","运动员","people",3,"n"],["champion","冠军","people",3,"n"],["opponent","敌手","people",3,"n"],
/* 物品 120 */
["device","装置","thing",3,"n"],["weapon","武器","thing",3,"n"],["shield","盾牌","thing",3,"n"],
["chain","锁链","thing",3,"n"],["lock","锁","thing",3,"n"],["trap","陷阱","thing",3,"n"],
["torch","火把","thing",3,"n"],["banner","旗帜","thing",3,"n"],["coin","硬币","thing",3,"n"],
["treasure","宝藏","thing",3,"n"],["fragment","碎片","thing",3,"n"],["tool","工具","thing",3,"n"],
["container","容器","thing",3,"n"],["material","材料","thing",3,"n"],["blade","刀刃","thing",3,"n"],
["sword","剑","thing",3,"n"],["dagger","匕首","thing",3,"n"],["spear","长矛","thing",3,"n"],
["arrow","箭","thing",3,"n"],["bow","弓","thing",3,"n"],["axe","斧","thing",3,"n"],
["armour","盔甲","thing",3,"n"],["helmet","头盔","thing",3,"n"],["cloak","斗篷","thing",3,"n"],
["robe","长袍","thing",3,"n"],["mask","面具","thing",3,"n"],["crown","王冠","thing",3,"n"],
["jewel","珠宝","thing",3,"n"],["amulet","护身符","thing",3,"n"],["charm","符咒","thing",3,"n"],
["scroll","卷轴","thing",3,"n"],["parchment","羊皮纸","thing",3,"n"],["manuscript","手稿","thing",3,"n"],
["journal","日志","thing",3,"n"],["diary","日记","thing",3,"n"],["ink","墨水","thing",3,"n"],
["seal","印章","thing",3,"n"],["barrel","木桶","thing",3,"n"],["crate","板条箱","thing",3,"n"],
["sack","麻袋","thing",3,"n"],["pouch","小袋","thing",3,"n"],["jar","罐子","thing",3,"n"],
["flask","烧瓶","thing",3,"n"],["bucket","水桶","thing",3,"n"],["saw","锯子","thing",3,"n"],
["screw","螺丝","thing",3,"n"],["bolt","螺栓","thing",3,"n"],["gear","齿轮","thing",3,"n"],
["lever","杠杆","thing",3,"n"],["machine","机器","thing",3,"n"],["motor","马达","thing",3,"n"],
["pump","水泵","thing",3,"n"],["pipe","管子","thing",3,"n"],["tube","试管","thing",3,"n"],
["cable","电缆","thing",3,"n"],["plug","插头","thing",3,"n"],["socket","插座","thing",3,"n"],
["circuit","电路","thing",3,"n"],["monitor","显示器","thing",3,"n"],["keyboard","键盘","thing",3,"n"],
["printer","打印机","thing",3,"n"],["laptop","手提电脑","thing",3,"n"],["gadget","小玩意","thing",3,"n"],
["robot","机器人","thing",3,"n"],["rocket","火箭","thing",3,"n"],["satellite","卫星","thing",3,"n"],
["telescope","望远镜","thing",3,"n"],["compass","罗盘","thing",3,"n"],["mattress","床垫","thing",3,"n"],
["cushion","靠垫","thing",3,"n"],["rug","小地毯","thing",3,"n"],["frame","框架","thing",3,"n"],
["cabinet","柜子","thing",3,"n"],["bench","长凳","thing",3,"n"],["stool","凳子","thing",3,"n"],
["broom","扫帚","thing",3,"n"],["brush","刷子","thing",3,"n"],["comb","梳子","thing",3,"n"],
["razor","剃刀","thing",3,"n"],["perfume","香水","thing",3,"n"],["sleeve","袖子","thing",3,"n"],
["collar","衣领","thing",3,"n"],["ribbon","丝带","thing",3,"n"],["thread","线","thing",3,"n"],
["cloth","布","thing",3,"n"],["fabric","织物","thing",3,"n"],["leather","皮革","thing",3,"n"],
["wool","羊毛","thing",3,"n"],["cotton","棉花","thing",3,"n"],["silk","丝绸","thing",3,"n"],
["statue","雕像","thing",3,"n"],["monument","纪念碑","thing",3,"n"],["pillar","石柱","thing",3,"n"],
["arch","拱门","thing",3,"n"],["brick","砖","thing",3,"n"],["cement","水泥","thing",3,"n"],
["contract","合同","thing",3,"n"],["receipt","收据","thing",3,"n"],["passport","护照","thing",3,"n"],
["licence","执照","thing",3,"n"],["label","标签","thing",3,"n"],["poster","海报","thing",3,"n"],
["magazine","杂志","thing",3,"n"],["novel","小说","thing",3,"n"],["dictionary","词典","thing",3,"n"],
["album","相册","thing",3,"n"],["portrait","肖像","thing",3,"n"],["sculpture","雕塑","thing",3,"n"],
["parcel","包裹","thing",3,"n"],["package","包装","thing",3,"n"],["luggage","行李","thing",3,"n"],
["backpack","背包","thing",3,"n"],["purse","手提包","thing",3,"n"],["puzzle","谜题","thing",3,"n"],
["instrument","乐器","thing",3,"n"],["drum","鼓","thing",3,"n"],["flute","长笛","thing",3,"n"],
["violin","小提琴","thing",3,"n"],["guitar","吉他","thing",3,"n"],["piano","钢琴","thing",3,"n"],
/* 自然 60 */
["cliff","悬崖","nature",3,"n"],["stream","溪流","nature",3,"n"],["swamp","沼泽","nature",3,"n"],
["dust","尘土","nature",3,"n"],["flame","火焰","nature",3,"n"],["ash","灰烬","nature",3,"n"],
["crystal","水晶","nature",3,"n"],["surface","表面","nature",3,"n"],["depth","深处","nature",3,"n"],
["silence","寂静","nature",3,"n"],["echo","回声","nature",3,"n"],["canyon","峡谷","nature",3,"n"],
["glacier","冰川","nature",3,"n"],["volcano","火山","nature",3,"n"],["earthquake","地震","nature",3,"n"],
["flood","洪水","nature",3,"n"],["drought","干旱","nature",3,"n"],["breeze","微风","nature",3,"n"],
["mist","薄雾","nature",3,"n"],["frost","霜","nature",3,"n"],["dew","露水","nature",3,"n"],
["hail","冰雹","nature",3,"n"],["lightning","闪电","nature",3,"n"],["tide","潮汐","nature",3,"n"],
["current","水流","nature",3,"n"],["horizon","地平线","nature",3,"n"],["sunlight","日光","nature",3,"n"],
["moonlight","月光","nature",3,"n"],["starlight","星光","nature",3,"n"],["peak","山顶","nature",3,"n"],
["slope","山坡","nature",3,"n"],["ridge","山脊","nature",3,"n"],["plain","平原","nature",3,"n"],
["meadow","草甸","nature",3,"n"],["marsh","湿地","nature",3,"n"],["shore","岸边","nature",3,"n"],
["bay","海湾","nature",3,"n"],["reef","礁石","nature",3,"n"],["clay","黏土","nature",3,"n"],
["ore","矿石","nature",3,"n"],["mineral","矿物","nature",3,"n"],["metal","金属","nature",3,"n"],
["timber","木材","nature",3,"n"],["coal","煤","nature",3,"n"],["iron","铁","nature",3,"n"],
["copper","铜","nature",3,"n"],["pebble","卵石","nature",3,"n"],["boulder","巨石","nature",3,"n"],
["gravel","砾石","nature",3,"n"],["dune","沙丘","nature",3,"n"],["climate","气候","nature",3,"n"],
["atmosphere","大气","nature",3,"n"],["oxygen","氧气","nature",3,"n"],["environment","环境","nature",3,"n"],
["pollution","污染","nature",3,"n"],["energy","能量","nature",3,"n"],["gravity","重力","nature",3,"n"],
["universe","宇宙","nature",3,"n"],["galaxy","星系","nature",3,"n"],["eclipse","日食","nature",3,"n"],
/* 动作 230 */
["discover","发现","verb",3,"v"],["survive","幸存","verb",3,"v"],["escape","逃脱","verb",3,"v"],
["defend","防御","verb",3,"v"],["attack","攻击","verb",3,"v"],["struggle","挣扎","verb",3,"v"],
["achieve","达成","verb",3,"v"],["require","需要","verb",3,"v"],["contain","包含","verb",3,"v"],
["reveal","揭示","verb",3,"v"],["avoid","避开","verb",3,"v"],["approach","接近","verb",3,"v"],
["vanish","消失","verb",3,"v"],["gather","聚集","verb",3,"v"],["whisper","低语","verb",3,"v"],
["crawl","爬行","verb",3,"v"],["swallow","吞下","verb",3,"v"],["bury","埋葬","verb",3,"v"],
["carve","雕刻","verb",3,"v"],["forge","锻造","verb",3,"v"],["betray","背叛","verb",3,"v"],
["endure","忍受","verb",3,"v"],["summon","召唤","verb",3,"v"],["awaken","唤醒","verb",3,"v"],
["abandon","抛弃","verb",3,"v"],["absorb","吸收","verb",3,"v"],["accuse","指控","verb",3,"v"],
["adapt","适应","verb",3,"v"],["admire","钦佩","verb",3,"v"],["admit","承认","verb",3,"v"],
["adopt","采纳","verb",3,"v"],["advise","建议","verb",3,"v"],["afford","负担得起","verb",3,"v"],
["announce","宣布","verb",3,"v"],["apologize","道歉","verb",3,"v"],["appear","出现","verb",3,"v"],
["apply","申请","verb",3,"v"],["argue","争论","verb",3,"v"],["arrange","安排","verb",3,"v"],
["arrest","逮捕","verb",3,"v"],["assist","协助","verb",3,"v"],["assume","假定","verb",3,"v"],
["attach","附上","verb",3,"v"],["attempt","尝试","verb",3,"v"],["attend","出席","verb",3,"v"],
["attract","吸引","verb",3,"v"],["behave","表现","verb",3,"v"],["bend","弯曲","verb",3,"v"],
["blame","责怪","verb",3,"v"],["bleed","流血","verb",3,"v"],["blend","混合","verb",3,"v"],
["bloom","开花","verb",3,"v"],["boil","煮沸","verb",3,"v"],["breathe","吸气","verb",3,"v"],
["broadcast","广播","verb",3,"v"],["burst","爆裂","verb",3,"v"],["calculate","计算","verb",3,"v"],
["cancel","取消","verb",3,"v"],["capture","俘获","verb",3,"v"],["celebrate","庆祝","verb",3,"v"],
["challenge","挑战","verb",3,"v"],["charge","充电","verb",3,"v"],["chase","追赶","verb",3,"v"],
["cheat","作弊","verb",3,"v"],["claim","声称","verb",3,"v"],["combine","结合","verb",3,"v"],
["command","命令","verb",3,"v"],["concentrate","集中","verb",3,"v"],["confess","坦白","verb",3,"v"],
["confirm","确认","verb",3,"v"],["confuse","使困惑","verb",3,"v"],["connect","连接","verb",3,"v"],
["conquer","征服","verb",3,"v"],["consider","考虑","verb",3,"v"],["consume","消耗","verb",3,"v"],
["control","控制","verb",3,"v"],["convince","说服","verb",3,"v"],["correct","改正","verb",3,"v"],
["crack","弄裂","verb",3,"v"],["crash","撞毁","verb",3,"v"],["create","创造","verb",3,"v"],
["criticize","批评","verb",3,"v"],["cure","治愈","verb",3,"v"],["curse","诅咒","verb",3,"v"],
["damage","损害","verb",3,"v"],["dare","敢于","verb",3,"v"],["deal","处理","verb",3,"v"],
["declare","宣告","verb",3,"v"],["decrease","减少","verb",3,"v"],["defeat","击败","verb",3,"v"],
["define","定义","verb",3,"v"],["deliver","递送","verb",3,"v"],["demand","要求","verb",3,"v"],
["deny","否认","verb",3,"v"],["depend","依赖","verb",3,"v"],["deserve","值得","verb",3,"v"],
["design","设计","verb",3,"v"],["develop","发展","verb",3,"v"],["devote","奉献","verb",3,"v"],
["dig","挖掘","verb",3,"v"],["disappear","不见","verb",3,"v"],["discuss","讨论","verb",3,"v"],
["dismiss","解雇","verb",3,"v"],["display","展示","verb",3,"v"],["divide","划分","verb",3,"v"],
["drag","拖拽","verb",3,"v"],["earn","赚得","verb",3,"v"],["embrace","拥抱","verb",3,"v"],
["employ","雇用","verb",3,"v"],["encourage","鼓励","verb",3,"v"],["engage","参与","verb",3,"v"],
["enter","进入","verb",3,"v"],["establish","建立","verb",3,"v"],["estimate","估计","verb",3,"v"],
["examine","审视","verb",3,"v"],["exchange","交换","verb",3,"v"],["exist","存在","verb",3,"v"],
["expand","扩大","verb",3,"v"],["explode","爆炸","verb",3,"v"],["explore","探索","verb",3,"v"],
["express","表达","verb",3,"v"],["extend","延伸","verb",3,"v"],["fade","消退","verb",3,"v"],
["fail","失败","verb",3,"v"],["feed","喂养","verb",3,"v"],["flee","逃离","verb",3,"v"],
["float","漂浮","verb",3,"v"],["flow","流动","verb",3,"v"],["fold","折叠","verb",3,"v"],
["force","强迫","verb",3,"v"],["forgive","原谅","verb",3,"v"],["freeze","冻结","verb",3,"v"],
["frighten","使害怕","verb",3,"v"],["glance","瞥见","verb",3,"v"],["glow","发亮","verb",3,"v"],
["govern","统治","verb",3,"v"],["grab","攫取","verb",3,"v"],["grant","授予","verb",3,"v"],
["greet","问候","verb",3,"v"],["guarantee","保证","verb",3,"v"],["handle","操控","verb",3,"v"],
["hang","悬挂","verb",3,"v"],["harm","伤害","verb",3,"v"],["haunt","缠扰","verb",3,"v"],
["heal","疗愈","verb",3,"v"],["hesitate","犹豫","verb",3,"v"],["hire","租用","verb",3,"v"],
["hunt","打猎","verb",3,"v"],["identify","辨认","verb",3,"v"],["ignore","忽视","verb",3,"v"],
["impress","打动","verb",3,"v"],["improve","改进","verb",3,"v"],["include","包括","verb",3,"v"],
["increase","增加","verb",3,"v"],["indicate","指示","verb",3,"v"],["inform","通知","verb",3,"v"],
["injure","弄伤","verb",3,"v"],["insist","坚持","verb",3,"v"],["inspire","激励","verb",3,"v"],
["install","安装","verb",3,"v"],["intend","打算","verb",3,"v"],["interrupt","打断","verb",3,"v"],
["introduce","介绍","verb",3,"v"],["invent","发明","verb",3,"v"],["invest","投资","verb",3,"v"],
["involve","牵涉","verb",3,"v"],["kick","踢","verb",3,"v"],["knock","敲","verb",3,"v"],
["lack","缺少","verb",3,"v"],["last","持续","verb",3,"v"],["launch","发射","verb",3,"v"],
["link","关联","verb",3,"v"],["load","装载","verb",3,"v"],["maintain","维持","verb",3,"v"],
["manage","管理","verb",3,"v"],["measure","测量","verb",3,"v"],["melt","融化","verb",3,"v"],
["mention","提到","verb",3,"v"],["mix","搅拌","verb",3,"v"],["observe","观察","verb",3,"v"],
["obtain","获得","verb",3,"v"],["occur","发生","verb",3,"v"],["operate","操作","verb",3,"v"],
["oppose","反对","verb",3,"v"],["overcome","克服","verb",3,"v"],["pack","打包","verb",3,"v"],
["paint","绘画","verb",3,"v"],["perform","表演","verb",3,"v"],["permit","允许","verb",3,"v"],
["persuade","劝服","verb",3,"v"],["praise","赞扬","verb",3,"v"],["prefer","更喜欢","verb",3,"v"],
["press","按压","verb",3,"v"],["prevent","阻止","verb",3,"v"],["produce","生产","verb",3,"v"],
["provide","提供","verb",3,"v"],["publish","出版","verb",3,"v"],["punish","惩罚","verb",3,"v"],
["pursue","追寻","verb",3,"v"],["raise","举起","verb",3,"v"],["react","反应","verb",3,"v"],
["realize","意识到","verb",3,"v"],["receive","收到","verb",3,"v"],["recognize","认出","verb",3,"v"],
["recommend","推荐","verb",3,"v"],["record","记录","verb",3,"v"],["recover","恢复","verb",3,"v"],
["reduce","缩减","verb",3,"v"],["refuse","拒绝","verb",3,"v"],["reject","驳回","verb",3,"v"],
["relax","放松","verb",3,"v"],["release","释放","verb",3,"v"],["remain","留存","verb",3,"v"],
["remind","提醒","verb",3,"v"],["remove","移除","verb",3,"v"],["replace","替换","verb",3,"v"],
["reply","回复","verb",3,"v"],["report","报告","verb",3,"v"],["represent","代表","verb",3,"v"],
["rescue","营救","verb",3,"v"],["research","研究","verb",3,"v"],["resist","抵抗","verb",3,"v"],
["respect","尊敬","verb",3,"v"],["respond","应答","verb",3,"v"],["rest","休息","verb",3,"v"],
["restore","修复","verb",3,"v"],["reward","奖赏","verb",3,"v"],["rise","升起","verb",3,"v"],
["risk","冒险","verb",3,"v"],["shatter","粉碎","verb",3,"v"],
/* 描述 190 */
["hollow","空心的","adj",3,"adj"],["fragile","脆弱的","adj",3,"adj"],["solid","坚固的","adj",3,"adj"],
["bitter","苦的","adj",3,"adj"],["cruel","残酷的","adj",3,"adj"],["gentle","温和的","adj",3,"adj"],
["silent","无声的","adj",3,"adj"],["endless","无尽的","adj",3,"adj"],["hidden","隐藏的","adj",3,"adj"],
["sacred","神圣的","adj",3,"adj"],["cursed","被诅咒的","adj",3,"adj"],["brave","勇敢的","adj",3,"adj"],
["greedy","贪婪的","adj",3,"adj"],["patient","有耐心的","adj",3,"adj"],["curious","好奇的","adj",3,"adj"],
["obvious","明显的","adj",3,"adj"],["certain","确定的","adj",3,"adj"],["possible","可能的","adj",3,"adj"],
["familiar","熟悉的","adj",3,"adj"],["absent","缺席的","adj",3,"adj"],["absolute","绝对的","adj",3,"adj"],
["abstract","抽象的","adj",3,"adj"],["accurate","准确的","adj",3,"adj"],["active","积极的","adj",3,"adj"],
["actual","实际的","adj",3,"adj"],["adequate","足够的","adj",3,"adj"],["alike","相似的","adj",3,"adj"],
["alive","活着的","adj",3,"adj"],["amazing","惊人的","adj",3,"adj"],["annoying","恼人的","adj",3,"adj"],
["artificial","人造的","adj",3,"adj"],["automatic","自动的","adj",3,"adj"],["available","可用的","adj",3,"adj"],
["average","平均的","adj",3,"adj"],["aware","察觉的","adj",3,"adj"],["awful","糟糕的","adj",3,"adj"],
["basic","基本的","adj",3,"adj"],["blank","空白的","adj",3,"adj"],["blind","失明的","adj",3,"adj"],
["bloody","血腥的","adj",3,"adj"],["blunt","钝的","adj",3,"adj"],["broad","宽阔的","adj",3,"adj"],
["brutal","残暴的","adj",3,"adj"],["capable","有能力的","adj",3,"adj"],["casual","随意的","adj",3,"adj"],
["central","中心的","adj",3,"adj"],["chief","主要的","adj",3,"adj"],["civil","民事的","adj",3,"adj"],
["complex","复杂的","adj",3,"adj"],["concrete","具体的","adj",3,"adj"],["convenient","方便的","adj",3,"adj"],
["crazy","疯狂的","adj",3,"adj"],["creative","有创意的","adj",3,"adj"],["critical","关键的","adj",3,"adj"],
["crowded","拥挤的","adj",3,"adj"],["damp","潮湿的","adj",3,"adj"],["deadly","致命的","adj",3,"adj"],
["decent","体面的","adj",3,"adj"],["delicate","精致的","adj",3,"adj"],["dense","密集的","adj",3,"adj"],
["desperate","拼命的","adj",3,"adj"],["detailed","详细的","adj",3,"adj"],["digital","数字的","adj",3,"adj"],
["direct","直接的","adj",3,"adj"],["distant","遥远的","adj",3,"adj"],["divine","神性的","adj",3,"adj"],
["domestic","家用的","adj",3,"adj"],["dull","枯燥的","adj",3,"adj"],["dusty","积灰的","adj",3,"adj"],
["efficient","高效的","adj",3,"adj"],["elegant","优雅的","adj",3,"adj"],["enormous","巨大的","adj",3,"adj"],
["entire","整个的","adj",3,"adj"],["equal","相等的","adj",3,"adj"],["essential","必要的","adj",3,"adj"],
["exact","确切的","adj",3,"adj"],["excellent","优秀的","adj",3,"adj"],["exotic","异国的","adj",3,"adj"],
["extra","额外的","adj",3,"adj"],["extreme","极端的","adj",3,"adj"],["faint","微弱的","adj",3,"adj"],
["fair","公平的","adj",3,"adj"],["false","虚假的","adj",3,"adj"],["fancy","花哨的","adj",3,"adj"],
["filthy","肮脏的","adj",3,"adj"],["final","最终的","adj",3,"adj"],["firm","坚定的","adj",3,"adj"],
["fit","合身的","adj",3,"adj"],["flexible","灵活的","adj",3,"adj"],["fluent","流利的","adj",3,"adj"],
["foolish","愚蠢的","adj",3,"adj"],["formal","正式的","adj",3,"adj"],["former","从前的","adj",3,"adj"],
["fortunate","幸运的","adj",3,"adj"],["frozen","冰冻的","adj",3,"adj"],["genuine","真诚的","adj",3,"adj"],
["giant","庞大的","adj",3,"adj"],["global","全球的","adj",3,"adj"],["gorgeous","华丽的","adj",3,"adj"],
["gradual","逐渐的","adj",3,"adj"],["grand","宏伟的","adj",3,"adj"],["grim","冷酷的","adj",3,"adj"],
["guilty","有罪的","adj",3,"adj"],["harsh","严厉的","adj",3,"adj"],["helpful","有帮助的","adj",3,"adj"],
["hostile","敌对的","adj",3,"adj"],["huge","巨型的","adj",3,"adj"],["humble","谦逊的","adj",3,"adj"],
["ideal","理想的","adj",3,"adj"],["identical","同一的","adj",3,"adj"],["idle","闲置的","adj",3,"adj"],
["illegal","非法的","adj",3,"adj"],["immense","广大的","adj",3,"adj"],["immediate","立刻的","adj",3,"adj"],
["independent","独立的","adj",3,"adj"],["indoor","室内的","adj",3,"adj"],["infinite","无限的","adj",3,"adj"],
["initial","最初的","adj",3,"adj"],["innocent","无辜的","adj",3,"adj"],["intense","强烈的","adj",3,"adj"],
["internal","内部的","adj",3,"adj"],["invisible","隐形的","adj",3,"adj"],["legal","合法的","adj",3,"adj"],
["liquid","液态的","adj",3,"adj"],["local","本地的","adj",3,"adj"],["loose","松的","adj",3,"adj"],
["loyal","忠诚的","adj",3,"adj"],["lucky","走运的","adj",3,"adj"],["mad","发疯的","adj",3,"adj"],
["magic","魔法的","adj",3,"adj"],["major","重大的","adj",3,"adj"],["massive","厚重的","adj",3,"adj"],
["mature","成熟的","adj",3,"adj"],["medical","医疗的","adj",3,"adj"],["mental","心理的","adj",3,"adj"],
["mighty","强大的","adj",3,"adj"],["mild","轻微的","adj",3,"adj"],["military","军事的","adj",3,"adj"],
["minor","次要的","adj",3,"adj"],["mobile","移动的","adj",3,"adj"],["moist","微湿的","adj",3,"adj"],
["mysterious","神秘的","adj",3,"adj"],["native","本土的","adj",3,"adj"],["natural","自然的","adj",3,"adj"],
["necessary","必需的","adj",3,"adj"],["negative","消极的","adj",3,"adj"],["neutral","中立的","adj",3,"adj"],
["noisy","嘈杂的","adj",3,"adj"],["numerous","众多的","adj",3,"adj"],["official","官方的","adj",3,"adj"],
["opposite","相反的","adj",3,"adj"],["ordinary","普通的","adj",3,"adj"],["original","原本的","adj",3,"adj"],
["outer","外部的","adj",3,"adj"],["painful","痛苦的","adj",3,"adj"],["partial","部分的","adj",3,"adj"],
["passive","被动的","adj",3,"adj"],["peaceful","和平的","adj",3,"adj"],["personal","个人的","adj",3,"adj"],
["physical","身体的","adj",3,"adj"],["pleasant","令人愉快的","adj",3,"adj"],["plenty","充足的","adj",3,"adj"],
["positive","正面的","adj",3,"adj"],["powerful","有力的","adj",3,"adj"],["practical","实用的","adj",3,"adj"],
["precious","珍贵的","adj",3,"adj"],["precise","精确的","adj",3,"adj"],["pregnant","怀孕的","adj",3,"adj"],
["present","在场的","adj",3,"adj"],["primary","首要的","adj",3,"adj"],["private","私人的","adj",3,"adj"],
["probable","大概的","adj",3,"adj"],["profound","深刻的","adj",3,"adj"],["proper","恰当的","adj",3,"adj"],
["pure","纯净的","adj",3,"adj"],["rapid","迅速的","adj",3,"adj"],["rare","稀有的","adj",3,"adj"],
["raw","生的","adj",3,"adj"],["realistic","现实的","adj",3,"adj"],["reasonable","合理的","adj",3,"adj"],
["regular","规律的","adj",3,"adj"],["relative","相对的","adj",3,"adj"],["reliable","可靠的","adj",3,"adj"],
["remote","偏远的","adj",3,"adj"],["rigid","僵硬的","adj",3,"adj"],["romantic","浪漫的","adj",3,"adj"],
["rotten","腐烂的","adj",3,"adj"],["royal","皇家的","adj",3,"adj"],["rural","乡村的","adj",3,"adj"],
["rusty","生锈的","adj",3,"adj"],
/* 时间 30 */
["century","世纪","time",3,"n"],["decade","十年","time",3,"n"],["delay","延迟","time",3,"v"],
["period","时期","time",3,"n"],["recent","最近的","time",3,"adj"],["sudden","突然的","time",3,"adj"],
["eternal","永恒的","time",3,"adj"],["dawn","黎明","time",3,"n"],["dusk","黄昏","time",3,"n"],
["twilight","暮色","time",3,"n"],["era","纪元","time",3,"n"],["instant","瞬间","time",3,"n"],
["pause","停顿","time",3,"n"],["interval","间隔","time",3,"n"],["duration","持续时间","time",3,"n"],
["deadline","截止日期","time",3,"n"],["anniversary","周年","time",3,"n"],["occasion","场合","time",3,"n"],
["event","事件","time",3,"n"],["phase","阶段","time",3,"n"],["cycle","周期","time",3,"n"],
["routine","惯例","time",3,"n"],["frequent","频繁的","time",3,"adj"],["constant","持续的","time",3,"adj"],
["previous","先前的","time",3,"adj"],["temporary","暂时的","time",3,"adj"],["permanent","永久的","time",3,"adj"],
["annual","每年的","time",3,"adj"],["monthly","每月的","time",3,"adj"],["weekly","每周的","time",3,"adj"],
/* 地点 60 */
["palace","宫殿","place",3,"n"],["temple","神庙","place",3,"n"],["prison","监狱","place",3,"n"],
["tunnel","隧道","place",3,"n"],["chamber","密室","place",3,"n"],["ruin","废墟","place",3,"n"],
["border","边界","place",3,"n"],["shelter","庇护所","place",3,"n"],["region","地区","place",3,"n"],
["path","小径","place",3,"n"],["fortress","要塞","place",3,"n"],["castle","城堡","place",3,"n"],
["gateway","门道","place",3,"n"],["dungeon","地牢","place",3,"n"],["cellar","地窖","place",3,"n"],
["vault","金库","place",3,"n"],["crypt","墓穴","place",3,"n"],["tomb","坟墓","place",3,"n"],
["graveyard","墓地","place",3,"n"],["shrine","神龛","place",3,"n"],["altar","祭坛","place",3,"n"],
["chapel","小教堂","place",3,"n"],["monastery","修道院","place",3,"n"],["courtyard","庭院","place",3,"n"],
["corridor","走廊","place",3,"n"],["hall","大厅","place",3,"n"],["balcony","阳台","place",3,"n"],
["attic","阁楼","place",3,"n"],["basement","地下室","place",3,"n"],["lobby","门厅","place",3,"n"],
["studio","工作室","place",3,"n"],["workshop","作坊","place",3,"n"],["laboratory","实验室","place",3,"n"],
["warehouse","仓库","place",3,"n"],["dock","码头","place",3,"n"],["pier","栈桥","place",3,"n"],
["lighthouse","灯塔","place",3,"n"],["settlement","定居点","place",3,"n"],["colony","殖民地","place",3,"n"],
["province","省份","place",3,"n"],["kingdom","王国","place",3,"n"],["empire","帝国","place",3,"n"],
["realm","领域","place",3,"n"],["territory","领土","place",3,"n"],["frontier","前线","place",3,"n"],
["outpost","前哨","place",3,"n"],["camp","营地","place",3,"n"],["route","路线","place",3,"n"],
["lane","巷子","place",3,"n"],["highway","公路","place",3,"n"],["avenue","大道","place",3,"n"],
["junction","交叉口","place",3,"n"],["platform","站台","place",3,"n"],["terminal","终点站","place",3,"n"],
["stadium","体育场","place",3,"n"],["arena","竞技场","place",3,"n"],["gallery","画廊","place",3,"n"],
["clinic","诊所","place",3,"n"],["orchard","果园","place",3,"n"],["vineyard","葡萄园","place",3,"n"],
/* 情绪 45 */
["fear","恐惧","feel",3,"n"],["hope","希望","feel",3,"n"],["anger","愤怒","feel",3,"n"],
["shame","羞耻","feel",3,"n"],["regret","后悔","feel",3,"n"],["relief","宽慰","feel",3,"n"],
["courage","勇气","feel",3,"n"],["despair","绝望","feel",3,"n"],["doubt","怀疑","feel",3,"n"],
["trust","信任","feel",3,"n"],["desire","渴望","feel",3,"n"],["grief","悲痛","feel",3,"n"],
["pride","自豪","feel",3,"n"],["envy","嫉妒","feel",3,"n"],["sorrow","悲伤","feel",3,"n"],
["delight","欣喜","feel",3,"n"],["terror","恐怖","feel",3,"n"],["panic","恐慌","feel",3,"n"],
["rage","暴怒","feel",3,"n"],["guilt","内疚","feel",3,"n"],["mercy","怜悯","feel",3,"n"],
["passion","热情","feel",3,"n"],["sympathy","同情","feel",3,"n"],["anxiety","焦虑","feel",3,"n"],
["stress","压力","feel",3,"n"],["temper","脾气","feel",3,"n"],["spirit","精神","feel",3,"n"],
["will","意志","feel",3,"n"],["memory","记忆","feel",3,"n"],["instinct","本能","feel",3,"n"],
["pleasure","愉悦","feel",3,"n"],["eager","热切的","feel",3,"adj"],["furious","狂怒的","feel",3,"adj"],
["gloomy","忧郁的","feel",3,"adj"],["weary","疲惫的","feel",3,"adj"],["joyful","喜悦的","feel",3,"adj"],
["hopeless","无望的","feel",3,"adj"],["fearful","畏惧的","feel",3,"adj"],["restless","不安的","feel",3,"adj"],
["ashamed","羞愧的","feel",3,"adj"],["content","满足的","feel",3,"adj"],["bold","大胆的","feel",3,"adj"],
["timid","胆怯的","feel",3,"adj"],["tender","温柔的","feel",3,"adj"],["fierce","凶猛的","feel",3,"adj"],
/* 数字 20 */
["billion","十亿","num",3,"num"],["trillion","万亿","num",3,"num"],["third","第三","num",3,"num"],
["fourth","第四","num",3,"num"],["fifth","第五","num",3,"num"],["sixth","第六","num",3,"num"],
["seventh","第七","num",3,"num"],["eighth","第八","num",3,"num"],["ninth","第九","num",3,"num"],
["tenth","第十","num",3,"num"],["triple","三倍的","num",3,"num"],["quantity","数量","num",3,"num"],
["amount","总额","num",3,"num"],["sum","总和","num",3,"num"],["majority","大多数","num",3,"num"],
["minority","少数","num",3,"num"],["fraction","分数","num",3,"num"],["decimal","小数","num",3,"num"],
["digit","数位","num",3,"num"],["unit","单位","num",3,"num"],
/* 副词 58 */
["abroad","在国外","adv",3,"adv"],["absolutely","绝对地","adv",3,"adv"],["afterwards","之后","adv",3,"adv"],
["anyway","无论如何","adv",3,"adv"],["apart","分开地","adv",3,"adv"],["aside","在一旁","adv",3,"adv"],
["backward","向后地","adv",3,"adv"],["barely","几乎不","adv",3,"adv"],["beforehand","事先","adv",3,"adv"],
["besides","此外","adv",3,"adv"],["briefly","简短地","adv",3,"adv"],["clearly","清楚地","adv",3,"adv"],
["closely","紧密地","adv",3,"adv"],["completely","完全地","adv",3,"adv"],["constantly","不断地","adv",3,"adv"],
["deeply","深深地","adv",3,"adv"],["directly","直接地","adv",3,"adv"],["downstairs","在楼下","adv",3,"adv"],
["eventually","最终","adv",3,"adv"],["exactly","确切地","adv",3,"adv"],["extremely","极其","adv",3,"adv"],
["fairly","相当","adv",3,"adv"],["forever","永远","adv",3,"adv"],["forward","向前地","adv",3,"adv"],
["frankly","坦率地","adv",3,"adv"],["further","更远地","adv",3,"adv"],["generally","通常地","adv",3,"adv"],
["gently","温柔地","adv",3,"adv"],["gradually","逐渐地","adv",3,"adv"],["highly","高度地","adv",3,"adv"],
["immediately","立即","adv",3,"adv"],["indeed","确实","adv",3,"adv"],["largely","大体上","adv",3,"adv"],
["lately","近来","adv",3,"adv"],["loudly","大声地","adv",3,"adv"],["mainly","主要地","adv",3,"adv"],
["meanwhile","与此同时","adv",3,"adv"],["merely","仅仅","adv",3,"adv"],["mostly","多半","adv",3,"adv"],
["naturally","自然地","adv",3,"adv"],["normally","正常地","adv",3,"adv"],["obviously","显然","adv",3,"adv"],
["otherwise","否则","adv",3,"adv"],["overall","总体上","adv",3,"adv"],["perfectly","完美地","adv",3,"adv"],
["personally","亲自","adv",3,"adv"],["possibly","或许","adv",3,"adv"],["previously","先前地","adv",3,"adv"],
["quietly","安静地","adv",3,"adv"],["rapidly","快速地","adv",3,"adv"],["rarely","很少","adv",3,"adv"],
["recently","最近","adv",3,"adv"],["regularly","定期地","adv",3,"adv"],["seldom","罕有地","adv",3,"adv"],
["seriously","严肃地","adv",3,"adv"],["shortly","不久","adv",3,"adv"],["simply","简单地","adv",3,"adv"],
["slightly","略微","adv",3,"adv"]
];

/* 派生索引 —— 加词后自动生效，不用手动维护 */
var WMAP = {};
WORDS.forEach(function(w){ WMAP[w[0]] = {en:w[0], cn:w[1], cat:w[2], lv:w[3] || 1, pos:w[4] || "n"}; });
var BYCAT = {};
WORDS.forEach(function(w){ (BYCAT[w[2]] = BYCAT[w[2]] || []).push(WMAP[w[0]]); });
/* 按词性分桶 —— Boss 的弱点就在这里面挑 */
var BYPOS = {};
WORDS.forEach(function(w){ (BYPOS[w[4] || "n"] = BYPOS[w[4] || "n"] || []).push(WMAP[w[0]]); });
/* 按难度分桶，出题时按章节挑桶 */
var BYLV = {1:[], 2:[], 3:[]};
WORDS.forEach(function(w){ BYLV[w[3] || 1].push(WMAP[w[0]]); });
var ALLW = WORDS.map(function(w){ return WMAP[w[0]]; });
